name: Run Tests

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: Run build:prod
        run: |
          npm run build:prod

      - name: Run build:test:prod
        run: |
          npm run build:test:prod

      - name: Run test
        run: |
          npm run test
